# Generated by Django 5.0.4 on 2024-05-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriberapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_s',
            old_name='otp',
            new_name='password',
        ),
    ]
