# Generated by Django 5.0.4 on 2024-05-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriberapp', '0002_rename_otp_user_s_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_s',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
